### ISSUE TITLE
Reflect on the highlights of 2018

### ISSUE THREAD

**Issue by andreakb** [digital-preservation-is-people/digital-preservation-is-people.github.io#15]
Hi all,
I'm drafting up a blog about the year in Digital Preservation is People, (the pull request is here: https://github.com/digital-preservation-is-people/digital-preservation-is-people.github.io/pull/14), and since this is a community blog, it would be great if you have time to take a look & edit/contribute as you see fit. 

We're especially looking for ideas of good things/incremental changes that happened last year. As an example, so far we have ipres2018 enacting a CoC, the DPC drafting an inclusion & diversity panel, & DLF calling for no more manels. 

Thank you!

**Comment by ablwr** [comment]
DLF also announced the beginning and planned continuation of funding people from HBCUs to the conference https://forum2018.diglib.org/fellowship-opportunities/#HBCU

**Comment by andreakb** [comment]
Thank you! I'll add it!
