### ISSUE TITLE
Post idea: #52fund

### ISSUE THREAD

**Issue by andreakb** [digital-preservation-is-people/digital-preservation-is-people.github.io#20]
I wonder if we should amplify what is going on with the SAA nominations and the #52fund. For those who aren't clued in, a petition signed by 52 SAA members (signed by some former SAA presidents, fellows, etc, If you also look at the signers of the petition, you'll see some digipres names in there too. ) overrode the the SAA nominating committee (an elected committee) by adding another VP nominee to the election slate, and it looks a lot like gate-keeping when you read more into it. There's more information in this tweet thread: https://twitter.com/gonzoarchivist/status/1217592802898522112 and there are great blogposts by Ruth Kitchin Tillman: https://ruthtillman.com/post/disappointed-society-of-american-archivists/ and one of the original nominees for VP, Courtney Chartier, https://toxicarchivist.wordpress.com/2020/01/16/white-like-me/

In response, Samantha Winn is organizing a fundraiser (#52fund) to support QTBIPOC folks joining SAA and/or attending the SAA annual meeting this year.https://docs.google.com/document/d/1bW7OMGahktEltnfKuSz7TppusPcl9Nw3iDRpwd9fh9Y/edit# 

Wondering if anyone here has the bandwidth, or is involved with the SAA (I'm not a member) and wants to write something up.

**Comment by kfrn** [comment]
I've never been involved in SAA ... haven't they had some other controversies in recent years?

I can't do a writeup - apart from everything else, I'm way too removed from the situation - but thanks for the links!

**Comment by andreakb** [comment]
I'm not up to date on all the controversies, but maybe the latest was the was the brown bag lunch thing. Ross pointed me to this excellent write-up about it from Eira Tansey: http://eiratansey.com/2019/08/01/peer-review-for-archivists-or-wtf-is-going-on-with-this-saa-pre-print/
